title: The Dry Needling Academy
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6503759
  brandStrength: 0.4924812
  lightness: 0.6729323
  brandColors:
    - '#ffffff'
    - '#7a7a7a'
    - '#34d5a3'
    - '#d3d3d3'
    - '#a7a7a7'
  rhythmicContrast: 0.5988185
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Dry Needling Academy
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3506981
layout_spectrum: 1
