name: Dry Needling Academy
favicon: null
layout_spectrum: 0.14906815625727177
typography_spectrum: 0.75839
title: The Dry Needling Academy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a7a7a'
    - '#34d5a3'
    - '#d3d3d3'
    - '#a7a7a7'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
