name: Dry Needling Academy
favicon: null
layout_spectrum: 0.14906815625727177
typography_spectrum: 0.750907254172489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7728568119928241
  lightness: 0.5551777873188257
  saturation: 0.03196467366069555
  rhythmicContrast: 0.24558553658425808
purpose: []
