title: The Dry Needling Academy
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7685285
  brandStrength: 0.8555317
  lightness: 0.9919441
  brandColors:
    - '#ffffff'
    - '#7a7a7a'
    - '#34d5a3'
    - '#d3d3d3'
    - '#a7a7a7'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Dry Needling Academy
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.750907254172489
layout_spectrum: 0.1490681562572718
